@base_url = http://localhost:3333
@access_token = {{authenticate.response.body.access_token}}

# @name register
POST {{base_url}}/users
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "12345678",
  "first_name": "John",
  "last_name": "Doe",
  "cpf": "523.065.281-01"
}

###

# @name authenticate
POST {{base_url}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "12345678"
}

###

# @name refresh
POST {{base_url}}/sessions/refresh
Content-Type: application/json

{
  "access_token": "{{access_token}}"
}

###

# @name get_user-profile
GET {{base_url}}/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# @name register-product
POST {{base_url}}/products
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "Batata"
}

###

# @name register-agribusiness
POST {{base_url}}/agribusinesses
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
 "caf": "agribusiness-caf",
 "name": "name of the agribusiness" 
}

###

# @name offer-products
POST {{base_url}}/offers
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "products": [
    {
      "product_id": "891399b5-e591-464a-b42a-c64eb13f85a2",
      "quantity": "2",
      "amount": "2",
      "weight": "3"
    }
  ]
}

###

# @name search-offers
GET {{base_url}}/offers?product=banana
Content-Type: application/json
Authorization: Bearer {{access_token}}
