@base_url = http://localhost:3333
@token = {{authenticate_with_password.response.body.token}}

# @name register
POST {{base_url}}/users
Content-Type: application/json

{
  "email": "timoteostifft@gmail.com",
  "cellphone": "51981280499",
  "password": "password",
  "first_name": "Timóteo",
  "last_name": "Stifft",
  "cpf": "04437220056"
}

###

# @name authenticate_with_password
POST {{base_url}}/auth
Content-Type: application/json

{
  "email": "admin@ecoo.com.br",
  "password": "12345678"
}

###

# @name authenticate-with-one-time-password
POST {{base_url}}/auth/otp
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "timoteostifft@gmail.com",
  "one_time_password": "607926"
}

###

# @name refresh
POST {{base_url}}/auth/refresh
Content-Type: application/json

{
  "token": "{{token}}"
}

###

# @name get_user-profile
GET {{base_url}}/me
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name register-agribusiness
POST {{base_url}}/agribusinesses
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "caf": "88888888",
 "name": "Agrocomércio do Timas"
}

###

# @name offer-products
POST {{base_url}}/offers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "products": [
    {
      "id": "0932460d-81c7-47ff-9ac7-1acb990e7cdc",
      "quantity_or_weight": 50,
      "price": "10"
    }
  ]
}

###

# @name search-offers
GET {{base_url}}/offers?product=queijo
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name order-products
POST {{base_url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "shipping_address": "test address",
  "cycle_id": "0932460d-81c7-47ff-9ac7-1acb990e7cdc",
  "payment_method": "PIX",
  "products": [
    {
      "id": "0932460d-81c7-47ff-9ac7-1acb990e7cdc",
      "quantity_or_weight": 50
    }
  ]
}

###

# @name update-agribusiness
PATCH {{base_url}}/agribusiness
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "caf": "1111221111111111",
  "name": "agribusiness updated name"  
}

###

# @name register-one-time-password
POST {{base_url}}/users/otp
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "timoteostifft@gmail.com"
}

###

# @name update-agribusiness-status
GET {{base_url}}/agribusiness/0c3ffa93-4f46-4c25-ad2d-403c3a6b1b39
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name search-products
GET{{base_url}}/products?name=Batata&page=1
Content-Type: application/json
Authorization: Bearer {{token}}

