version: "3"
services:
  postgres:
    container_name: ecoo-postgres
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"

  qdrant:
    container_name: ecoo_vector_db
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  qdrant_scripts:
    container_name: ecoo_vector_db_scripts
    build:
      context: ./qdrant
      dockerfile: ./Dockerfile
      args:
        - REQUIREMENTS_TXT_PATH=./requirements.txt
    volumes:
      - ./products.json:/app/products.json
      - ./qdrant/seed.py:/app/seed.py
      - ./nlp/src/utils/:/app/utils/
      - ./nlp/src/qdrant_service.py:/app/qdrant_service.py
    depends_on:
      - qdrant

  nlp:
    container_name: ecoo_nlp
    build:
      context: ./nlp/
      dockerfile: ./Dockerfile
      args:
        - REQUIREMENTS_TXT_PATH=./requirements.txt
    volumes:
      - ./nlp/src/:/app/
    ports:
      - "5000:5000"
    depends_on:
      - qdrant

  smtp4dev:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"

  server:
    container_name: ecoo-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
    depends_on:
      - postgres
      - smtp4dev
      - qdrant
    network_mode: "host"
