version: "3"
services:
  postgres:
    container_name: ecoo-postgres
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"
    profiles: ["dev", "deploy"]

  smtp4dev:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"
    profiles: ["dev"]

  server: &server
    container_name: ecoo-deploy-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
      - ./.env:/app/.env
    network_mode: "host"
    restart: always
    depends_on:
      - postgres
    profiles: ["deploy"]

  dev-server:
    <<: *server
    container_name: ecoo-dev-server
    depends_on:
      - smtp4dev
    profiles: ["dev"]
