version: "3"
services:
  database:
    container_name: ecoo-db
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"

  smtp4dev:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"

  server:
    container_name: ecoo-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/ecoo_db?schema=public
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
    depends_on:
      - database
      - smtp4dev
