version: "3"
services:
  postgres:
    container_name: ecoo-postgres
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"

  qdrant:
    container_name: ecoo-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  nlp:
    container_name: ecoo-nlp
    build:
      context: ./nlp/
      dockerfile: ./Dockerfile
      args:
        - REQUIREMENTS_TXT_PATH=./requirements.txt
    volumes:
      - ./nlp/src/:/app/
      - ./products.json:/app/products.json
    ports:
      - "5000:5000"
    depends_on:
      - qdrant

  smtp4dev:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"

  server:
    container_name: ecoo-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
    depends_on:
      - postgres
      - smtp4dev
      - qdrant
    network_mode: "host"
    restart: always
