version: "3"
services:
  postgres:
    container_name: ecoo-postgres
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecoo_db
    ports:
      - "5432:5432"

  qdrant:
    container_name: ecoo-qdrant
    image: qdrant/qdrant:latest
    environment:
      QDRANT_URL: "http://localhost:6333/"
    ports:
      - "6333:6333"

  nlp:
    container_name: ecoo-nlp
    build:
      context: ./nlp/
      dockerfile: ./Dockerfile
      args:
        - REQUIREMENTS_TXT_PATH=./requirements.txt
    volumes:
      - ./nlp/src/:/app/
      - ./products.json:/app/products.json
    ports:
      - "5000:5000"
    environment:
      NLP_URL: "${NLP_URL:-http://localhost:5000}"
      EXPECTED_SIMILARITY_SCORE: "${EXPECTED_SIMILARITY_SCORE:-0.6}"
    depends_on:
      - qdrant

  smtp4dev:
    container_name: ecoo-smtp
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"

  server:
    container_name: ecoo-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./prisma:/app/prisma
    environment:
      ENV: "${ENV:-dev}"
      SERVER_URL: "${SERVER_URL:-http://localhost}"
      PORT: "${PORT:-3333}"
      JWT_SECRET: "${JWT_SECRET:-token}"
      SESSION_DURATION_IN_DAYS: "${SESSION_DURATION_IN_DAYS:-7}"
      POSTGRES_URL: "${DATABASE_URL:-postgresql://postgres:postgres@localhost:5432/ecoo_db?schema=public}"
      QDRANT_URL: "${QDRANT_URL:-http://localhost:6333/}"
      NLP_URL: "${NLP_URL:-http://localhost:5000}"
      EXPECTED_SIMILARITY_SCORE: "${EXPECTED_SIMILARITY_SCORE:-0.6}"
      PAYMENTS_PROCESSOR_API_KEY: "${PAYMENTS_PROCESSOR_API_KEY:-blablabla}"
      ECOO_EMAIL: "${ECOO_EMAIL:-suporte@ecoo.org.br}"
      ECOO_EMAIL_PASSWORD: "${ECOO_EMAIL_PASSWORD:-Jhui$vh8}"
      SMTP_HOST: "${SMTP_HOST:-localhost}"
      SMTP_PORT: "${SMTP_PORT:-2525}"
    depends_on:
      - postgres
      - smtp4dev
      - qdrant
    network_mode: "host"
