version: "3"
services:
  smtp4dev:
    container_name: smtp-server
    image: rnwood/smtp4dev:v3
    ports:
      - "3010:80"
      - "2525:25"

  node-server:
    container_name: node-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - SMTP_HOST=smtp4dev
      - SMTP_PORT=25
    volumes:
      - ./src:/app/src
      - ./test:/app/test
