import { qdrantSeedProducts } from "../../qdrant/seed-products";
import { prisma } from "../../src/infra/database/prisma-service";

const productsData: { type: string; products: string[] }[] = [
  {
    type: "Hortaliças, legumes e verduras",
    products: [
      "Abóbora Cabotiá",
      "Abóbora Japonesa",
      "Abóbora Moranga",
      "Abóbora Paulista",
      "Abobrinha Brasileira",
      "Abobrinha Italiana",
      "Acelga",
      "Agrião",
      "Aipim",
      "Alcachofra",
      "Alecrim",
      "Alface Americana",
      "Alface Crespa",
      "Alface Lisa",
      "Alface Mimosa",
      "Alface Quatro Estações",
      "Alface Roxa",
      "Alho",
      "Alho Poró",
      "Batata Baroa",
      "Batata Branca",
      "Batata Doce Amarela",
      "Batata Doce Rosada",
      "Batata Rosa",
      "Berinjela Comum",
      "Berinjela Japonesa",
      "Beterraba",
      "Brócolis",
      "Cebola",
      "Cebola Roxa",
      "Cebolinha",
      "Cenoura",
      "Chuchu",
      "Coentro",
      "Cogumelo",
      "Couve",
      "Couve Bruxelas",
      "Couve-Flor",
      "Erva-Doce",
      "Espinafre",
      "Gengibre",
      "Hortelã",
      "Inhame",
      "Louro",
      "Manjericão",
      "Mostarda",
      "Nabo",
      "Palmito",
      "Pepino",
      "Pimenta Cambuci",
      "Pimenta Malagueta",
      "Pimenta Vermelha",
      "Pimentão Amarelo",
      "Pimentão Verde",
      "Pimentão Vermelho",
      "Pimenta Dedo-de-moça",
      "Quiabo",
      "Rabanete",
      "Repolho",
      "Rúcula",
      "Salsa",
      "Salsão",
      "Tomate Cereja",
      "Tomate Gaúcho",
      "Tomate Italiano",
      "Tomate Longa Vida",
      "Tomilho",
      "Vagem",
    ],
  },
  {
    type: "Frutas",
    products: [
      "Abacate",
      "Abacaxi",
      "Acerola",
      "Ameixa",
      "Amora",
      "Araçá",
      "Banana Caturra",
      "Banana Maçã",
      "Banana Nanica",
      "Banana Prata",
      "Bergamota",
      "Butiá",
      "Caqui",
      "Carambola",
      "Cereja",
      "Figo",
      "Framboesa",
      "Goiaba",
      "Jabuticaba",
      "Laranja do Céu",
      "Laranja Pera",
      "Laranja Umbigo",
      "Limão Bergamota",
      "Limão Taiti",
      "Maçã Nacional Fuji",
      "Maçã Nacional Gala",
      "Mamão Formosa",
      "Mamão Papaya",
      "Manga",
      "Maracujá Azedo",
      "Maracujá Doce",
      "Melancia",
      "Melão Amarelo",
      "Melão Casca de Carvalho",
      "Morango",
      "Pera",
      "Uva",
    ],
  },
  {
    type: "Cerais e grãos",
    products: [
      "Amendoim",
      "Arroz Branco",
      "Arroz Cateto",
      "Arroz Integral",
      "Arroz Parboilizado",
      "Ervilha Comum",
      "Ervilha Torta",
      "Favas",
      "Feijão Azuki",
      "Feijão Branco",
      "Feijão Carioca",
      "Feijão Fradinho",
      "Feijão Preto",
      "Feijão Vermelho",
      "Grão de Bico",
      "Lentilha",
      "Milho",
    ],
  },
  {
    type: "Origem animal",
    products: [
      "Queijo Colonial",
      "Ricota",
      "Leite",
      "Mel",
      "Ovo Branco",
      "Ovo de Codorna",
      "Ovo Vermelho",
      "Galinha",
      "Porco",
      "Ovelha",
      "Boi",
    ],
  },
];

export async function seedProducts() {
  await prisma.product.deleteMany();
  await prisma.productType.deleteMany();

  await prisma.productType.createMany({
    data: productsData.map(({ type }) => ({ name: type })),
  });

  const productsTypes = await prisma.productType.findMany();

  await prisma.product.createMany({
    data: productsData.flatMap((item) =>
      item.products.map((product) => ({
        name: product,
        type_id: productsTypes.find(
          (productType) => item.type === productType.name
        )!.id,
      }))
    ),
  });

  const products = await prisma.product.findMany();

  await qdrantSeedProducts(products);
}
