name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.9.0
          cache: "npm"
      - run: npm ci
      - run: npm run test
        env:
          ENV: test
          SERVER_URL: http://localhost
          PORT: 3333
          SESSION_DURATION_IN_DAYS: 30
          ECOO_EMAIL: suporte@ecoo.com.br
          FRONT_URL: https://produtor.ecoo.org.br
